---
title: "Self-made-man"
author: ""
date: "2021-4-4"
categories: [Analyysi, Eriarvoisuus]
image: ""
---

Yhdysvaltojen perustajaisä Benjamin Franklinin omaelämänkerrallinen teos \*The Autobiography of Benjamin Franklin\* julkaistiin englanniksi vuonna 1793 pari vuotta hänen kuolemansa jälkeen. Kirjasta tuli jättimenestys ja sitä pidetään yhtenä vaikutusvaltaisimpana omaelämänkerrallisena teoksena. Benjamin Franklinin nousu köyhyydestä mittaamattomaan varallisuuteen loi esimerkillisen pohjan seuraavina vuosisatoina julkaistaviin erilaisiin menestyskirjallisiin tuotoksiin, laulujen aiheisiin ja Hollywood-elokuviin, jotka levisivät laajalti Yhdysvalloissa ja myös maan ulkopuolella. Kaikkien haavekuvissa oli olla seuraava Franklinin kaltainen self-made man, joka vaatimattomista oloista lähteneenä lopulta saavuttaisi ahkeruudellaan ja omilla ansioillaan merkittävän varallisuuden ja korkean aseman.

Yhdysvalloissa self-made man -myyttiä pidetään ainutlaatuisena kansallisena luomuksena, amerikkalaisena keksintönä. Professori Heike Paul kertoo \*The Myths That Made America\* -kirjassaan myytin olevan utopistinen visio tasa-arvoisesta yhteiskunnasta, jossa sosiaalinen mobiliteetti on suurta. Siinä ilmenee individualistinen ja sosiaalidarwinistinen logiikka, jonka mukaan jokainen on vastuussa itsestään ja kollektiivinen vastuu yksittäisen kansalaisen hyvinvoinnista on vähäistä. 1700-luvulta lähtien Amerikkaa mainostettiin maallisena paratiisina, missä jokaisella oli yhdenvertaiset mahdollisuudet nousta ryysyistä rikkauksiin. Ajatus kirjailtiin niin ikään Yhdysvaltojen itsenäisyysjulistukseen, jonka tekstiä myös Benjamin Franklin oli muotoilemassa. Sen mukaan kaikki ihmiset oli luotu tasa-arvoisiksi ja heillä oli luovuttamaton oikeus elämään, vapauteen ja onnen tavoitteluun. Amerikan uudenlainen utopia oli valtava houkutus Euroopan ihmisille, jotka olivat mantereellaan köyhyyteen kahlittuina sääty-yhteiskuntien, uskontojen ja kuninkaiden ikeen alle. Vuosisatojen ajan aina näihin päiviin saakka miljoonat siirtolaiset, myös suomalaiset, olivat pyrkineet löytämään sateenkaaren pään juuri Amerikan yhdysvalloista.

Myytti tuli mieleeni, kun seurasin sosiaalisessa mediassa keskustelua nettoveronmaksajuudesta eli siitä, että on maksanut enemmän veroja kuin mitä on saanut elämänsä aikana tulonsiirtoina. Eräille se oli kaikessa ylimielisyydessään ja huvittavuudessaan kuin suomalainen versio amerikkalaisesta self-made manista. Heille nousu suomalaiseksi nettoveronmaksajaksi näyttäytyy oman ahkeruuden ja ansioiden tuloksena ja nettoveronsaajat vain liian laiskoina ja osaamattomina. Heidän ilmeisten olemassa olevien taitojen lisäksi tähän yhtälöön ei heille sovi lisäarvo, jonka he ovat saaneet valtion maksaman koulutuksen, terveydenhuollon, tie- ja rautatieverkoston ja turvallisuuden myötä, eikä ne onnelliset sattumukset, jotka he ovat vanhemmiltaan saaneet syntymäpaikkana ja rahallisena tai geenien perintönä\-\--monista muista elämän suunnittelemattomista sattumuksista nyt puhumattakaan.

Yhdysvalloissa onnenonkijat ovat saaneet yhä useammin pettyä self-made man -unelmaan. Vuoden 2020 \*The Global Social Mobility Index\* jättää Yhdysvaltojen sosiaalisessa mobiliteetissa korkean tulotason maista keskimääräistä alimmalle sijalle. Varallisuuserojen myötä materiaalinen menestys jää yhä useammalta saavuttamatta, luokkarajoja on entistä vaikeampaa ylittää, eikä epäonnen sattuessa kunnon turvaverkkoa ole\-\--kuten Covid-19 -kriisi on monelle yhdysvaltalaiselle karmivalla tavalla osoittanut. Ekonomisti Branko Milanović on esittänyt erinomaisessa \*Capitalism, Alone\* -kirjassaan vanhojen teollisuusmaiden, erityisesti Yhdysvaltojen, varallisuuserojen johtuvan kuudesta seikasta.

1.  Omistajien ja työntekijöiden välinen kuilu levenee, kun omistajien varallisuus kasvaa suhteessa työntekijöihin. Omistajat kasvattavat taloudellista ja poliittista vaikutusvaltaa investoimalla poliittisen kontrollin saamiseen ja sen säilyttämiseen.

2.  Varallisuus on erittäin keskittynyttä. Yhdysvalloissa rikkain 10% omistaa lähes kaiken omistamisen arvoisen rahoitusvarallisuuden.

3.  Mitä rikkaampi henkilö on, sitä enemmän ja hajautetummin hänellä on erilaisia omistuksia: osakkeita, kiinteistöjä ja muita rahoitusinstrumentteja.

4.  Toisin kuin 1800-luvun tuotoillaan elävä omistava luokka, niin nykyään suuria pääomatuloja saavat eivät lepäile vain laakereillaan, vaan ovat taipuvaisia saamaan myös korkeita palkkatuloja. Yhdysvalloissa lähes 30% niistä kotitalouksista, jotka pääomatulojen osalta kuuluvat ylimpään desiilin, saavat myös ansiotuloja, joilla päästään kaikista rikkaimpaan desiiliin. Määrä on kaksinkertaistunut vuodesta 1980.

5.  Yksi varallisuuseroja eniten määrittäviä tekijöitä on homogamia, eli puoliso valitaan yhä useammin samasta sosioekonomisesta viiteryhmästä.

6.  Varallisuuden hyödyt elintason, terveyden ja koulutuksen osalta siirtyvät sukupolvelta toiselle. Vanhempien ja lasten tulotasoissa on vahva korrelaatio.

Ei pidä ymmärtää väärin. Edellä mainitut seikat sisältävät erittäin positiivisia historiallisia kehityskulkuja. Ranskan vallankumouksen jälkeen kansoja alistavat kuninkaat, uskonnot ja lopulta myös sääty-yhteiskunta koki perusteellisia tappioita ja kansallisvaltioita alettiin rakentamaan vapauksien ja tasa-arvon varaan. Läntinen maailma on nyt paljon tasa-arvoisempi kuin 1800-luvun klassisen kapitalismin kulta-aikaan: naiset ovat työmarkkinoilla, omistava luokka ei elä ainoastaan pääomatuloillaan, rikkauksiin voi päästä palkkatyöllä, puolisoksi valitaan samankaltaisessa elämäntilanteessa oleva henkilö ja myös lapsiin panostetaan sekä aikaa että rahaa. Nämä ovat siis erittäin hyviä ja kannatettavia asioita! Taloustieteilijät lienevät melko yksimielisiä siitä, että taloudellinen eriarvoisuus ei käytännössä ole ongelma, jos kaikki vaurastuvat, vaikka osa vaurastuisi enemmän. Se on jopa suotavaa.

Taloudellinen eriarvoisuus on yhteiskunnallinen haitta, jos se aiheuttaa pysyvää huono-osaisuutta ja rikkaiden monopolivoimaa poliittisella kentällä. Tällaisia merkkejä on jo olemassa ja Branko Milanovićin mielestä se on pitkällä aikavälillä liberaalin meritokraattisen kapitalismin suurimpia uhkia. Yhdysvalloissa kaikkein rikkaimmat voivat vaikuttaa politiikkaan heitä hyödyttävällä tavalla. Vuoden 2016 vaalikampanjan lahjoituksista peräti 40 prosenttia toteutti rikkaimman prosentin ylin prosentti (ei ole typo). Se tuskin oli pelkkää hyväntekeväisyyttä. Myös koulutus on eriytynyttä, eikä keskiluokalla tahdo olla enää varaa kouluttaa lapsiaan. Yhdysvaltojen parhaimpiin korkeakouluihin saapuu enemmän opiskelijoita tulonjaon ylimmästä prosentista kuin koko alimmasta 60 prosentista. Vaurauden lisäämiseksi Milanović esittää muun muassa kansankapitalismia, jossa pieni- ja keskituloisia verohelpotuksin houkuteltaisiin omistamaan enemmän. Tämä ei kuitenkaan Milanovićin mukaan riitä. Hän kannattaa tinkimättömästi perintöveroa, joka hänen mielestään olisi omiaan parantamaan yhteiskunnissa mahdollisuuksien tasa-arvoa.

Milanovićin verotukselliset ideat eivät ole uusia, eikä siten miellytä monia, varsinkaan Yhdysvalloissa. Maan historia ja individualistiset ihanteet, kuten self-made man -myytti, ovat olleet Yhdysvalloissa laissez-faire kapitalismiin ja yrittäjyyteen kannustava tekijä, jotka ovat osaltaan synnyttäneet amerikkalaiseen yhteiskuntaan ulospäinsuuntautuneen, kunnianhimoisen ja periksiantamattomuuden identiteetin. Toisaalta ihanteet ja myytit ovat myös osa Yhdysvaltalaisen kahtiajakautumisen vuosisataista jatkumoa. Historialliset pelot vapauksien menettämisestä ovat luoneet vastakkainasettelun siitä, kuinka pitkälle valtion käsi voi ulottua ihmisten elämään ja taskuihin. Osa haluaisi parantaa menestymisen mahdollisuuksia kasvattamalla valtion roolia erilaisten palveluiden ja etuuksien maksajana, toisten mielestä jo nykyinenkin järjestelmä puuttuu liiaksi heidän perustuslaillisiin ja itsenäisyysjulistuksen lupaamiin vapauksiin. Valtion kontrollin lisääminen voi osan mielestä johtaa noidankehään kohti tyranniaa. Molemmat ovat argumentoituja tulkintoja. Kaikesta huolimatta ilman kunnollista tukiverkkoa valtava taloudellinen eriarvoisuus supistaa huono-osaisten menestymismahdollisuuksia Yhdysvalloissa.

Toisin kuin amerikkalainen järjestelmä, Suomen pohjoismainen hyvinvointivaltiomalli pyrkii tukemaan menestymistä kollektiivisesti. Yhteiskunnan sosiaalista mobiliteettia mittaava The Global Social Mobility Index rankkaa Suomen kolmanneksi tasapisteisiin Norjan kanssa. Viiden parhaan joukkoon pääsevät kaikki Pohjoismaat. Suomessa sosiaalinen mobiliteetti luokkien välillä on edelleen mahdollista ja epäonnistenkin on mahdollista menestyä. Näköpiirissä on silti haasteita. Korkeasti kehittyneelle hyvinvointivaltiolle globalisaatio, ikääntyvä väestö, maaseudun näivettyminen ja laajemmassa mitassa mahdollinen matalan koulutustason omaavien ihmisten maahanmuutto on vaikea yhtälö ratkaistavaksi. Varallisuuserot ovat jo kasvaneet. Suomessa viimeisen kolmenkymmenen vuoden aikana varakkain kymmenys on kasvattanut varallisuuttaan, mutta vähävaraisin 50 prosenttia ei sitä ole juurikaan tehnyt. Myös keskiluokan varallisuuden kasvu on ollut viime vuosikymmenellä heikkoa. Vähävaraisimman varallisuus on pääsääntöisesti kiinni asunnoissa ja niiden arvo on laskenut. Rikkaimmilla on monipuolisemmin rahoitusvarallisuutta, joka on tuottanut kasvua. Varallisuuserojen kasvaessa pitkän aikavälin vaarana on, että huono-osaisuus kasautuu, yhteiskunnalliset palvelut köyhempien ja rikkaimpien välillä eriytyvät, kansalaisten luottamus instituutioihin ja kanssaihmisiin rapautuu ja rikkaimpien halu osallistua yhä kasvavien yhteisten palvelujen maksajina heikkenee. Näitä ajatuksia on jo havaittavissa muun muassa Anu Kantolan ja Hanna Kuuselan \*Huipputuloiset-\*kirjassa esitetyissä mielipiteissä ja sosiaalisen median keskusteluissa nettoveronmaksajista ja -saajista.

Kapitalismi luo vaurautta, mutta kapitalismiin sisäsyntyisesti kuuluva eriarvoisuuskehitys tarvitsee kollektiivisen turvaverkon epäonnisten varalle sekä uudenlaisia poliittisia ratkaisuja, jotta mahdollisimman monella olisi paremmat mahdollisuudet menestyä, erityisesti Yhdysvalloissa. Suomessa uudet kansankapitalistiset avaukset, kuten hyvin menestynyt osakesäästötili tai ajatukset sen asettamisesta osaksi äitiyspakkausta voisivat olla kuin Branko Milanovićin kynästä. Niiden soisi kannustavan suomalaiset pois lottokansan perinteestä, joka olisi omiaan kasvattamaan pieni- ja keskituloisten varallisuutta. Samalla on pohdittava, kuinka pidämme yhteiskunnassa mahdollisimman monet mukana, niin että verotus pysyisi kaikkien kannalta hyväksyttävyyden rajoissa. Vuosikymmenen pituista heikkoa talouskasvua Suomella ei ole mahdollisuutta enää pitkittää. Luottamus instituutioihin ja kanssaihmisiin on jatkossakin kansakuntien yhteinen etu.
